<a href="https://colab.research.google.com/github/essanchristian-maker/DI-Bootcamp/blob/master/Week3_Day1_Exercises_XP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

🌟 Exercise 1 : Array Creation and Manipulation


In [2]:
import numpy as np

Array = np.arange(10)
print(Array)

[0 1 2 3 4 5 6 7 8 9]


🌟 Exercise 2 : Type Conversion and Array Operations


In [6]:
import numpy as np

arr = np.array([3.14, 2.17, 0, 1, 2])
arr[0:2] = ([3, 2])
print(arr)

[3. 2. 0. 1. 2.]


🌟 Exercise 3 : Working with Multi-Dimensional Arrays


In [9]:
import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array.reshape(3,3)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers


In [13]:
import numpy as np

array = np.random.rand(4, 5)
array_rounded = np.round(array, 2)
print(array_rounded)

[[0.13 0.63 0.23 0.56 0.57]
 [0.6  0.55 0.41 0.84 0.24]
 [0.07 0.07 0.4  0.43 0.37]
 [0.8  0.57 0.97 0.48 0.78]]


🌟 Exercise 5 : Indexing Arrays


In [21]:
import numpy as np

array_2D = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print("second row:", array_2D[2])

second row: [21 22 23 22 22]


🌟 Exercise 6 : Reversing elements


In [23]:
import numpy as np

array = np.arange(10)
print(array)
reversed_array = array[::-1]
print(reversed_array)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


🌟 Exercise 7 : Identity Matrix


In [25]:
import numpy as np

Array = np.eye(4)
print(Array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


🌟 Exercise 8 : Simple Aggregate Funcs


In [26]:
import numpy as np

array = np.arange(10)

total   = np.sum(array)
average = np.mean(array)

print(f"Sum: {total}, Average: {average}")


Sum: 45, Average: 4.5


🌟 Exercise 9 : Create Array and Change its Structure


In [27]:
import numpy as np

array = np.arange(1, 21)
matrix = array.reshape(4, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


🌟 Exercise 10 : Conditional Selection of Values


In [28]:
import numpy as np

array = np.arange(1, 10)
odd_numbers = array[array % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]
