<a href="https://colab.research.google.com/github/essanchristian-maker/DI-Bootcamp/blob/master/Week3_Day1_Exercises_XP_Ninja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# ============================================================
# Exercise 1 : Replacement de la valeur max dans une matrice
# ============================================================

import numpy as np

# Génération d'une matrice aléatoire 5x5 avec valeurs entre 0 et 1
matrix = np.random.rand(5, 5)
print("Matrice originale :")
print(matrix.round(2))

# Repérage de l'index de la valeur maximale
# argmax retourne l'index dans le tableau aplati → on l'utilise tel quel sur la copie aplatie
matrix[matrix == matrix.max()] = 0

print("\nMatrice après remplacement du max par 0 :")
print(matrix.round(2))

Matrice originale :
[[0.27 0.55 0.66 0.89 0.27]
 [0.92 0.26 0.92 0.14 0.96]
 [0.08 0.81 0.14 0.11 0.13]
 [0.98 0.52 0.65 0.72 0.72]
 [0.95 0.77 0.72 0.59 0.07]]

Matrice après remplacement du max par 0 :
[[0.27 0.55 0.66 0.89 0.27]
 [0.92 0.26 0.92 0.14 0.96]
 [0.08 0.81 0.14 0.11 0.13]
 [0.   0.52 0.65 0.72 0.72]
 [0.95 0.77 0.72 0.59 0.07]]


In [5]:
# ============================================================
# Exercise 2 : Valeurs communes entre deux tableaux
# ============================================================

import numpy as np

# Pour obtenir des valeurs communes, on utilise des entiers aléatoires
# (sinon np.random.rand donne quasi jamais 2 fois la même valeur)
arr1 = np.random.randint(0, 10, size=5)
arr2 = np.random.randint(0, 10, size=5)

print("Tableau 1 :", arr1)
print("Tableau 2 :", arr2)

# np.intersect1d retourne les valeurs uniques communes aux deux tableaux
common = np.intersect1d(arr1, arr2)
print("\nValeurs communes :", common)

Tableau 1 : [9 2 5 7 3]
Tableau 2 : [9 0 5 7 4]

Valeurs communes : [5 7 9]


In [7]:
# ============================================================
# Exercise 3 : Tri ascendant et descendant
# ============================================================

import numpy as np

# Création d'un tableau 1D aléatoire de 10 valeurs entre 0 et 1
arr = np.random.rand(10)
print("Tableau original :", arr.round(2))

# Tri ascendant : np.sort retourne une copie triée du plus petit au plus grand
ascending = np.sort(arr)
print("\nAscendant  :", ascending.round(2))

# Tri descendant : on retourne le tableau ascendant avec slicing inversé [::-1]
descending = np.sort(arr)[::-1]
print("Descendant :", descending.round(2))

Tableau original : [0.76 0.09 0.03 0.99 0.43 0.8  0.22 0.37 0.91 0.49]

Ascendant  : [0.03 0.09 0.22 0.37 0.43 0.49 0.76 0.8  0.91 0.99]
Descendant : [0.99 0.91 0.8  0.76 0.49 0.43 0.37 0.22 0.09 0.03]


In [8]:
# ============================================================
# Exercise 4 : Rang d'une matrice
# ============================================================

import numpy as np

# Génération d'une matrice 4x4 aléatoire
# Quasi sûr d'avoir rang = 4 car les valeurs aléatoires sont indépendantes
matrix = np.random.rand(4, 4)
print("Matrice :")
print(matrix.round(2))

# np.linalg.matrix_rank calcule le nombre de lignes/colonnes linéairement indépendantes
rank = np.linalg.matrix_rank(matrix)
print(f"\nRank : {rank}")

# Bonus : exemple avec matrice dépendante (rang < 4)
matrix_dep = np.array([
    [1, 2, 3, 4],
    [2, 4, 6, 8],   # ligne 2 = 2 × ligne 1
    [1, 1, 1, 1],
    [3, 3, 3, 3],   # ligne 4 = 3 × ligne 3
])
print(f"\nMatrice avec lignes dépendantes → Rank : {np.linalg.matrix_rank(matrix_dep)}")

Matrice :
[[0.67 0.24 0.68 0.32]
 [0.95 0.01 0.92 0.39]
 [0.97 0.12 0.81 0.04]
 [0.69 0.21 0.   0.12]]

Rank : 4

Matrice avec lignes dépendantes → Rank : 2


In [9]:
# ============================================================
# Exercise 5 : Tableau avec bordure de 1 et intérieur de 0
# ============================================================

import numpy as np

# Méthode 1 : commencer avec des 1 partout, puis mettre l'intérieur à 0
arr = np.ones((5, 5), dtype=int)
arr[1:-1, 1:-1] = 0   # slicing : on garde la 1ère et dernière ligne/colonne intactes

print("Tableau bordure :")
print(arr)

# Méthode 2 : np.pad ajoute une bordure autour d'un tableau de zéros
inner = np.zeros((3, 3), dtype=int)
arr2 = np.pad(inner, pad_width=1, mode='constant', constant_values=1)

print("\nMême résultat avec np.pad :")
print(arr2)

Tableau bordure :
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

Même résultat avec np.pad :
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
