<a href="https://colab.research.google.com/github/essanchristian-maker/DI-Bootcamp/blob/master/Week3_Day1_Exercises_XP_Gold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 1 : Minimum and Maximum of Random Array


In [7]:
import numpy as np

# Créer un tableau 5x5 avec des valeurs aléatoires
array = np.random.rand(5,5)

# Trouver le min et le max
minimum = np.round(np.min(array), 2)
maximum = np.round(np.max(array), 2)

print(f"Min: {minimum}, Max: {maximum}")


Min: 0.01, Max: 0.99


Exercise 2 : Matrix Normalization


In [21]:
import numpy as np

# Créer une matrice 3x3 aléatoire
array = np.random.rand(3, 3)

# Normalisation : (valeur - moyenne) / écart-type
mean = np.mean(array)
std  = np.std(array)

Array = (array - mean) / std

print(np.round(Array, 2))

[[ 0.34  0.85 -1.51]
 [ 0.92 -0.6   1.02]
 [-0.52  1.02 -1.52]]


Exercise 3 : Evenly Spaced Elements in Array


In [22]:
import numpy as np

# 50 éléments espacés uniformément entre 0 et 10
array = np.linspace(0, 10, 50)
print(array)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


Exercise 4 : Matrix Multiplication


In [30]:
import numpy as np

# Créer une matrice 5x3
A = np.random.rand(5, 3)

# Créer une matrice 3x2
B = np.random.rand(3, 2)

# Produit matriciel
result = np.dot(A, B)

print(np.round(result, 2))

[[1.25 1.7 ]
 [0.89 1.21]
 [1.31 1.77]
 [0.57 0.88]
 [0.83 1.41]]


Exercise 5


In [31]:
import numpy as np

# Matrice A : 3x4
A = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

# Matrice B : 4x2
B = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])

# Produit matriciel
result = A @ B   # équivalent à np.dot(A, B)

print("Matrice A:\n", A)
print("Matrice B:\n", B)
print("Résultat A @ B:\n", result)

Matrice A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matrice B:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Résultat A @ B:
 [[ 50  60]
 [114 140]
 [178 220]]
